### ISSUE TITLE
[周读]

### ISSUE THREAD

**Issue by Rubicker** [Rubicker/tips#11]
## 12个Chrome调试知识
- Animation inspection
设置速度以检视动画，拖动可以到达某一帧,做动画的时候很有用
![1](https://cloud.githubusercontent.com/assets/17511710/21445661/cbc82030-c8f6-11e6-8e36-2cf29b989d7d.gif)

- 设备截图
通过开启`show device frame`，然后点击`Capture screenshot`即可得到一个带有相应手机壳的截图
    > 笔者得到的截图都有很大区域的黑色边框，原因尚不清楚

- console中的$0
在Console面板中输入`$0`,会给出你在`Element`面板中选中元素的DOM形式展现的对象。若希望展现为JS对象格式，可以输入`console.dir($0)`

- console中的箭头函数
主要是可以减少`Shift`+`Enter`次数，文中还强调了在Chrome 56版本后，有一个特性[`smart return`](https://developers.google.com/web/updates/2016/10/devtools-digest#console)可以在你按下`Enter`后智能识别是需要换行还是执行代码(某些特定场景下才有效，如写循环的时候)

- 选择器搜索
在Element面板中按下`Ctrl`+`F`进行搜索，可以按照字符串，选择器以及[XPath](https://en.wikipedia.org/wiki/XPath)进行搜索

- 调试颜色
可以使用吸管吸取颜色，或者选择页面已存在的某个颜色等等
![image](https://cloud.githubusercontent.com/assets/17511710/21446166/9f9a931a-c8fd-11e6-8978-7153b42788a1.png)

- 检测被渲染的字体
在Element面板下Computed一栏中可以找到Rendered Fonts，在这里可以看到哪些字体被渲染

- 直接修改页面中的文字
在Console面板输入`document.designMode = 'on'`即可开启编辑模式，此时就可以随意编辑网页上的所有文字。

- Filmstrip
在Network面板中开启`Capture screenshots`可以记录网站从载入到完成的快照，双击查看快照。

- network面板下的过滤筛选
通过filter可以筛选资源列表，下方是资源类型，也可以通过域名domain来筛选。

- 黑色主题
在preference中选择主题

- snippets

**Comment by Rubicker** [comment]
## 8个很有用的HTML5标签
- `<mark>`
用来指示相关性，比如搜索某个词，将搜索结果中的相同词汇标记出来
- `<small>`
一般我们只是用来减小文字大小，而这个标签的真正用法是用来降低权重的
- `<q>`/`<blockquote>`
引用，小的用`<q>`,大的用`<blockquote>`

**Comment by Rubicker** [comment]
### 基本的HTML5模版
```html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <!--<title>是<head>唯一强制要求的标签-->
  <title>The HTML5 Herald</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

  <link rel="stylesheet" href="css/styles.css?v=1.0">
  
  <!--It should be noted that if you’re using a JavaScript library that 
deals with HTML5 features or the new APIs, it’s possible that it will 
already have the HTML5-enabling script present; in this case, 
you could remove reference to the script. One example of this would 
be Modernizr, a JavaScript library that detects modern HTML and CSS features.
 Modernizr gives you the option to include code that enables the HTML5 
elements in older versions of IE, so the shiv would be redundant. 
We take a closer look at Modernizr in Appendix A.-->
  <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
  <![endif]-->
</head>

<body>
  <script src="js/scripts.js"></script>
</body>
</html>
```
> [The meta element](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element)
> 原文链接[A Basic HTML5 Template For Any Project](https://www.sitepoint.com/a-basic-html5-template/?utm_source=frontendfocus&utm_medium=email)

**Comment by Rubicker** [comment]
## Debug的艺术
作者将debug分为三个阶段:
- Replicate(查找bug)
- Isolate(理解bug)
- Eliminate(解决bug)
### Replicate
查找bug可以说是整项Debug流程中最为艰难的一部分。

**Comment by Rubicker** [comment]
### 使用真实网络环境进行测试
主要介绍了一些工具的使用
> 原文链接: [Testing with Realistic Networking Conditions](http://calendar.perfplanet.com/2016/testing-with-realistic-networking-conditions/?utm_source=frontendfocus&utm_medium=email)

**Comment by Rubicker** [comment]
## 你真的了解CSS中的`display`吗?

**Comment by Rubicker** [comment]
## 12个鲜为人知的CSS事实
- `border-radius`属性可以使用斜杠语法
  譬如:
  ```css
  .box {
    border-radius: 35px 25px 30px 20px / 35px 30px 20px 25px;
  }
  ```
  官方文档中这样写道:
  > If values are given before and after the slash, then the values before the slash set the horizontal radius and the values after the slash set the vertical radius. If there is no slash, then the values set both radii equally.

  > [Border-radius generator MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Background_and_Borders/Border-radius_generator)

- `font-weight`可以接受相关关键字
  不仅可以设置为`normal`,`bold`或者是数字，还可以设置为`border`和`lighter`。
  > One font weight darker/lighter than the parent element (among the available weights of the font).

- `outline-offset`属性
以前只了解`outline`这个属性:
  > Outlines differ from borders in the following ways:
   > - Outlines do not take up space, they are drawn above the content.
    >- Outlines may be non-rectangular. They are rectangular in Gecko/Firefox. But e.g. Opera draws a non-rectangular shape around a construct。(类似于包裹)
而`outline-offset`就是用来规定`outline`与内容区域之间的距离，需要说明的一点是`outline-offset`需要单独设定，不包括在`outline`缩写之中。
  
- `table-layout`
  调整表格内容布置
   > [Fixed Table Layouts](https://css-tricks.com/fixing-tables-long-strings/)

- `vertical-align`
  > When not applied to table cells, the vertical-align property follows these basic rules:
   >  - It works only on inline or inline-block elements.
   > - It has no effect on the contents of an element but instead it changes the alignment of the element itself in relation to other inline or inline-block elements.
   >  - It can be affected by text/font settings like line-height and by the size of adjacent inline or inline-block elements.

- `::first-letter`
智能，不是很简单的取第一个字母

- 在HTML类名中可以使用非法字符
- 动画循环次数可以使用小数值
`animation-iteration-count`的值不仅可以使用整数，还可以使用分数

- 动画属性简写时可能会因为动画名字而无法运行
  ```css
  @keyframes reverse {
    from {
      left: 0;
   }

    to {
      left: 300px;
    }
  }

  .example {
    animation: reverse 2s 1s;
  }
  ```
  上述动画无法运行，因为reverse是`animation-direction`的一个有效值，而将其作为动画名传给`animation`属性简写，则会造成无法运行的情况(在不缩写的情况下可以运行)

- 可以选择一定范围的元素
   ```css
   /*选择7到14的元素*/
   ol li:nth-child(n+7):nth-child(-n+14) {
     background: lightpink;
   }
   ```
   > To explain exactly what this is doing: In the first part of the chain, the expression says “select the 7th element, then every element after that”. The second part says “select the 14th element, and every element before that.” But since the selectors are chained, each limits the previous one’s scope. So the second part of the chain doesn’t allow the first part to go past 14 and the first part of the chain doesn’t allow the second part to go back past 7.

- 伪元素可以被应用于空元素

**Comment by Rubicker** [comment]
## 如何在限定宽度的父级中设置一个全屏宽的容器?
> The issue is: how do we make a full-browser-width container when we're inside a limited-width parent?

以下为默认代码:
```html
<!-- parent -->
<main>

  <p>Stuff.</p>

  <!-- container we want to be full width -->
  <figure class="full-width">
    <!-- could be whatever content -->
    <img src="dog.jpg" alt="">
  </figure>

</main>
```

### 若已知父级宽度为百分比宽度
那么我们就可以按照比例将container撑开:
```css
main {
  width: 60%;
  margin: 0 auto;
  /* creates 20% margins on either side */
}
.full-width {
  /* 1/3 of 60% = the 20% margin on either side */
  margin-left: -33.33%;
  margin-right: -33.33%;
}
```

### 若已知父级宽度为非百分比宽度
> The amount we want to "pull" to the left and right is half the width of the browser window plus half the width of the parent. (Assuming the parent is centered.)
```css
@media (min-width: 500px) {
  main {
    width: 500px;
    margin: 0 auto;
  }
  .full-width {
    margin-left: calc(-100vw / 2 + 500px / 2);
    margin-right: calc(-100vw / 2 + 500px / 2);
  }
}
```
也可以使用`translate`属性:
```css
@media (min-width: 40em) {
  .full-width {
    width: 100vw;
    transform: translateX(calc((40em - 100vw)/2));
  }
}
```
更兼容的写法:
```css
/*把回退样式写在该样式前面*/
@supports (width: 100vw) {
  .full-width {
    width: 100vw;
  }
  @media all and (min-width: 40rem) {
    .full-width {
       transform: translateX(calc((40rem - 100vw)/2));
    }
  }
}
```
据测试在Edge下无效，在Chrome下偶尔会应用，只有在FF下正常。

### 无需`clac()`
首先用`left:50%`将container左侧边缘置于屏幕正中央，然后利用`margin-left: -50vw`将其拉伸到左屏幕边缘:
```css
.full-width {
  width: 100vw;
  position: relative;
  left: 50%;
  right: 50%;
  margin-left: -50vw;
  margin-right: -50vw;
}
```
需要设定`right:50%`和`margin-right: -50vw`的原因是，有可能网页设置了`direction: rtl`。所以如上设置更为保险。
__需要注意的是此方法同上述方法都需要父级元素完全居中__

> 原文链接: [Full Width Containers in Limited Width Parents](https://css-tricks.com/full-width-containers-limited-width-parents/?utm_source=frontendfocus&utm_medium=email)
