### ISSUE TITLE
CSS学习之overflow

### ISSUE THREAD

**Issue by Rubicker** [Rubicker/tips#8]
## 基本属性
- visible(默认值)
- hidden
- scroll
- auto
- inherit

1.在IE8+下还有`overflow-x`和`overflow-y`属性:
- 若`overflow-x`和`overflow-y`相同，则等同于直接设置`overflow`
- 若两者不相同，且其中一个值被赋予`visible`,另外一个值被赋予`hidden`,`scroll`或`auto`，则`visible`会被重置为`auto

2.`overflow`作用的前提:
- 非`display:inline`
- 对应方位的尺寸限制(width/height/max-width/max-height/absolute)
- 对于单元格td等，还需设置table为`table-layout: fixed`

3.在IE7下，文字越多，按钮两侧padding留白越大，而其他浏览器中留白不会随文字多少改变,如何解决这个问题呢?
给所有按钮添加`overflow: visible`

### 出现滚动条条件:
- `overflow: auto`/`overflow: scroll`
- 内容超出其父级区域

### `<body>`/`<html>`与滚动条
无论什么浏览器，默认滚动条均来自于`<html>`,而不是`<body>`
IE7-默认: `html {overflow-y: scroll}`
IE8+默认:`html {overflow: auto}`
因此想要去除页面默认滚动条，只需要:
```css
html {overflow: hidden}
```

### 计算滚动高度
Chrome下: `document.body.scrollTop`
其他浏览器: `document.documentElement.scrollTop`
```javascript
//向后兼容的写法
var st = document.documentElement.scrollTop || document.body.scrollTop
```

### `overflow`的`padding-bottom`缺失现象
```css
.box {
  width: 400px;
  height: 100px;
  padding: 100px 0;
  overflow: auto;
}
```
在Chrome下容器内滚动可以出现上下padding，而在其他浏览器中padding消失了,所以会造成滚动高度不相同

### 滚动条的宽度机制
滚动条会占用容器的可用宽度或高度
如何获取滚动条宽度?
容器总宽度-容器内内容`clientWidth`

### 水平居中跳动问题的修复
```css
.container {
  width: 1150px;
  margin: 0 auto
}
```
由于滚动条的出现，`auto`会重新计算剩余宽度，所以会造成页面跳动，应当如何解决呢?
- 让页面默认显示滚动条
- 预留位置
  ```css
  //该方法本人未试验成功，待进一步检验
  .container {
     padding-left: calc(100vw - 100%)
  }
  ```
### iOS原生滚动回弹效果
```
//可以实现原生滚动效果，触底触顶都会有回弹效果
-webkit-overflow-scrolling: touch;
```

## overflow与BFC
除`visible`之外均可触发BFC

- 用来清除浮动
- 避免margin穿透问题
