### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by evantianx** [Rubicker/tips#90]
CSS Pitfalls: 

- No encapsulation
- No variables
- Not compostable
- Bad modularity primitives
- Global
- Beating-into-submission-driven-development

**Comment by evantianx** [comment]
- Parent Selector (&)
  
  ```css
  .button {
    color: #333;
  }
  .them-dark .button {
    color: #fff;
  }
  ```
 
  ```sass
   .button {
    color: #333;
    .theme-dark & {
      color: #fff;
    }
   }
   ```
